### ISSUE TITLE
Proposal for EET compatibility

### ISSUE THREAD

**Issue by RoxanneSHS** [vnebelung/bgsodde#1]
In TP2

```
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
STRING_SET_RANGE #34000 #71374 USING ~bgsodde/dialogs.tra~
END

ACTION_IF GAME_IS ~eet~ THEN BEGIN
STRING_SET_RANGE #234000 #271374 USING ~bgsodde/dialogs.tra~
END
```

Note last string here is 71374 which is the last one in my games. The tra file adds some 30 more that do not exist in my game, so I am not sure where those come from in the mod.

**Comment by vnebelung** [comment]
> Note last string here is 71374 which is the last one in my games. The tra file adds some 30 more that do not exist in my game, so I am not sure where those come from in the mod.

The translation is based on strings that were part of the translation database of Beamdog for SoD, until it was rejected as an official translation. No additional strings were added from my side.

I do not know at all what other mods are using which strings, so I will not change anything in this point, sorry.

**Comment by vnebelung** [comment]
With release v2021-03-01 EET integration should be fine.
